spring:
  application:
    name: ms-items 
  config:
    import: 
    - optional:configserver:http://root:s3cr3t@localhost:8081
    
#
#  data:
#      mongodb:
#        uri: mongodb+srv://trainingdbnttdata:zMaT0bwJ86xps4wN@proyectobootcamp.jyiov.mongodb.net/items
#  
#server:
#  port: 9091
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    enabled: false
#  instance:
#    hostname: localhost